"""Compatibility facade for Textual-free TheWorldHarness CSS constants."""

from __future__ import annotations

from worldforge.harness.tui_base_styles import (
    BREADCRUMB_DEFAULT_CSS,
    CONFIRM_DELETE_SCREEN_DEFAULT_CSS,
    HELP_SCREEN_DEFAULT_CSS,
    HOME_SCREEN_DEFAULT_CSS,
    JUMP_CARD_DEFAULT_CSS,
    PLACEHOLDER_SCREEN_DEFAULT_CSS,
    PROVIDER_STATUS_PILL_DEFAULT_CSS,
    RUN_INSPECTOR_SCREEN_DEFAULT_CSS,
    RUNS_SCREEN_DEFAULT_CSS,
    THE_WORLD_HARNESS_APP_CSS,
)
from worldforge.harness.tui_provider_styles import (
    BENCHMARK_SCREEN_DEFAULT_CSS,
    EVAL_SCREEN_DEFAULT_CSS,
    PROVIDERS_SCREEN_DEFAULT_CSS,
    REGISTER_PROVIDER_MODAL_DEFAULT_CSS,
)
from worldforge.harness.tui_robotics_styles import (
    ROBOTICS_SHOWCASE_APP_CSS,
    ROBOTICS_TABLETOP_HELP_SCREEN_CSS,
)
from worldforge.harness.tui_world_styles import (
    EDIT_OBJECT_SCREEN_DEFAULT_CSS,
    NEW_WORLD_SCREEN_DEFAULT_CSS,
    WORLD_EDIT_SCREEN_DEFAULT_CSS,
    WORLDS_SCREEN_DEFAULT_CSS,
)

__all__ = [
    "BENCHMARK_SCREEN_DEFAULT_CSS",
    "BREADCRUMB_DEFAULT_CSS",
    "CONFIRM_DELETE_SCREEN_DEFAULT_CSS",
    "EDIT_OBJECT_SCREEN_DEFAULT_CSS",
    "EVAL_SCREEN_DEFAULT_CSS",
    "HELP_SCREEN_DEFAULT_CSS",
    "HOME_SCREEN_DEFAULT_CSS",
    "JUMP_CARD_DEFAULT_CSS",
    "NEW_WORLD_SCREEN_DEFAULT_CSS",
    "PLACEHOLDER_SCREEN_DEFAULT_CSS",
    "PROVIDERS_SCREEN_DEFAULT_CSS",
    "PROVIDER_STATUS_PILL_DEFAULT_CSS",
    "REGISTER_PROVIDER_MODAL_DEFAULT_CSS",
    "ROBOTICS_SHOWCASE_APP_CSS",
    "ROBOTICS_TABLETOP_HELP_SCREEN_CSS",
    "RUNS_SCREEN_DEFAULT_CSS",
    "RUN_INSPECTOR_SCREEN_DEFAULT_CSS",
    "THE_WORLD_HARNESS_APP_CSS",
    "WORLDS_SCREEN_DEFAULT_CSS",
    "WORLD_EDIT_SCREEN_DEFAULT_CSS",
]
